#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 7

enum {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_AT = 3,
  anon_sym_SEMI = 4,
  anon_sym_COMMA = 5,
  anon_sym_DOLLAR = 6,
  anon_sym_TILDE = 7,
  anon_sym_BANG = 8,
  anon_sym_PIPE = 9,
  anon_sym_QMARK = 10,
  anon_sym_PERCENT = 11,
  anon_sym_POUND = 12,
  anon_sym_PLUS = 13,
  anon_sym_DASH = 14,
  anon_sym_STAR = 15,
  anon_sym_STAR_STAR = 16,
  anon_sym_SLASH = 17,
  anon_sym_GT = 18,
  anon_sym_LT = 19,
  anon_sym_EQ = 20,
  anon_sym_COLON = 21,
  anon_sym_CARET = 22,
  anon_sym__ = 23,
  anon_sym_DOT = 24,
  sym_ident = 25,
  sym_literalString = 26,
  sym_literalNumber = 27,
  sym_literalDecimal = 28,
  sym_lineComment = 29,
  sym_docComment = 30,
  sym_source_file = 31,
  sym_block = 32,
  sym__line = 33,
  sym_op = 34,
  sym_opDecl = 35,
  sym_opType = 36,
  sym_earlyOpType = 37,
  sym_opSet = 38,
  sym_opCall = 39,
  sym_opBuiltin = 40,
  sym_opBranch = 41,
  sym_opAlu = 42,
  sym_aluFunc = 43,
  sym__params = 44,
  sym__expr = 45,
  sym_scope = 46,
  sym__modifierScope = 47,
  sym__identScope = 48,
  sym__scopePath = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym__params_repeat1 = 51,
  aux_sym__modifierScope_repeat1 = 52,
  aux_sym__scopePath_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT] = "@",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_TILDE] = "~",
  [anon_sym_BANG] = "!",
  [anon_sym_PIPE] = "|",
  [anon_sym_QMARK] = "\?",
  [anon_sym_PERCENT] = "%",
  [anon_sym_POUND] = "#",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_SLASH] = "/",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_CARET] = "^",
  [anon_sym__] = "_",
  [anon_sym_DOT] = ".",
  [sym_ident] = "ident",
  [sym_literalString] = "literalString",
  [sym_literalNumber] = "literalNumber",
  [sym_literalDecimal] = "literalDecimal",
  [sym_lineComment] = "lineComment",
  [sym_docComment] = "docComment",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym__line] = "_line",
  [sym_op] = "op",
  [sym_opDecl] = "opDecl",
  [sym_opType] = "opType",
  [sym_earlyOpType] = "earlyOpType",
  [sym_opSet] = "opSet",
  [sym_opCall] = "opCall",
  [sym_opBuiltin] = "opBuiltin",
  [sym_opBranch] = "opBranch",
  [sym_opAlu] = "opAlu",
  [sym_aluFunc] = "aluFunc",
  [sym__params] = "_params",
  [sym__expr] = "_expr",
  [sym_scope] = "scope",
  [sym__modifierScope] = "_modifierScope",
  [sym__identScope] = "_identScope",
  [sym__scopePath] = "_scopePath",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__params_repeat1] = "_params_repeat1",
  [aux_sym__modifierScope_repeat1] = "_modifierScope_repeat1",
  [aux_sym__scopePath_repeat1] = "_scopePath_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym__] = anon_sym__,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_ident] = sym_ident,
  [sym_literalString] = sym_literalString,
  [sym_literalNumber] = sym_literalNumber,
  [sym_literalDecimal] = sym_literalDecimal,
  [sym_lineComment] = sym_lineComment,
  [sym_docComment] = sym_docComment,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym__line] = sym__line,
  [sym_op] = sym_op,
  [sym_opDecl] = sym_opDecl,
  [sym_opType] = sym_opType,
  [sym_earlyOpType] = sym_earlyOpType,
  [sym_opSet] = sym_opSet,
  [sym_opCall] = sym_opCall,
  [sym_opBuiltin] = sym_opBuiltin,
  [sym_opBranch] = sym_opBranch,
  [sym_opAlu] = sym_opAlu,
  [sym_aluFunc] = sym_aluFunc,
  [sym__params] = sym__params,
  [sym__expr] = sym__expr,
  [sym_scope] = sym_scope,
  [sym__modifierScope] = sym__modifierScope,
  [sym__identScope] = sym__identScope,
  [sym__scopePath] = sym__scopePath,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__params_repeat1] = aux_sym__params_repeat1,
  [aux_sym__modifierScope_repeat1] = aux_sym__modifierScope_repeat1,
  [aux_sym__scopePath_repeat1] = aux_sym__scopePath_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_literalString] = {
    .visible = true,
    .named = true,
  },
  [sym_literalNumber] = {
    .visible = true,
    .named = true,
  },
  [sym_literalDecimal] = {
    .visible = true,
    .named = true,
  },
  [sym_lineComment] = {
    .visible = true,
    .named = true,
  },
  [sym_docComment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_op] = {
    .visible = true,
    .named = true,
  },
  [sym_opDecl] = {
    .visible = true,
    .named = true,
  },
  [sym_opType] = {
    .visible = true,
    .named = true,
  },
  [sym_earlyOpType] = {
    .visible = true,
    .named = true,
  },
  [sym_opSet] = {
    .visible = true,
    .named = true,
  },
  [sym_opCall] = {
    .visible = true,
    .named = true,
  },
  [sym_opBuiltin] = {
    .visible = true,
    .named = true,
  },
  [sym_opBranch] = {
    .visible = true,
    .named = true,
  },
  [sym_opAlu] = {
    .visible = true,
    .named = true,
  },
  [sym_aluFunc] = {
    .visible = true,
    .named = true,
  },
  [sym__params] = {
    .visible = false,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym__modifierScope] = {
    .visible = false,
    .named = true,
  },
  [sym__identScope] = {
    .visible = false,
    .named = true,
  },
  [sym__scopePath] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__modifierScope_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__scopePath_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_cond = 1,
  field_expr = 2,
  field_func = 3,
  field_name = 4,
  field_path = 5,
  field_root = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_cond] = "cond",
  [field_expr] = "expr",
  [field_func] = "func",
  [field_name] = "name",
  [field_path] = "path",
  [field_root] = "root",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_path, 2},
    {field_root, 0},
    {field_root, 1},
  [4] =
    {field_expr, 3},
    {field_name, 1},
  [6] =
    {field_func, 1},
  [7] =
    {field_expr, 3},
    {field_name, 1},
    {field_value, 5},
  [10] =
    {field_cond, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(17);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '$') ADVANCE(15);
      if (lookahead == '%') ADVANCE(20);
      if (lookahead == '*') ADVANCE(26);
      if (lookahead == '+') ADVANCE(22);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(30);
      if (lookahead == '?') ADVANCE(19);
      if (lookahead == '@') ADVANCE(12);
      if (lookahead == '^') ADVANCE(34);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '|') ADVANCE(18);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == '~') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(26);
      if (lookahead == '+') ADVANCE(22);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '^') ADVANCE(34);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(41);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(17);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '$') ADVANCE(15);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '?') ADVANCE(19);
      if (lookahead == '@') ADVANCE(12);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '|') ADVANCE(18);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == '~') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(41);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym__);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_literalString);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_literalNumber);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_literalDecimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_lineComment);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_lineComment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym_literalString] = ACTIONS(1),
    [sym_literalNumber] = ACTIONS(1),
    [sym_literalDecimal] = ACTIONS(1),
    [sym_lineComment] = ACTIONS(1),
    [sym_docComment] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(53),
    [sym__line] = STATE(4),
    [sym_op] = STATE(4),
    [sym_opDecl] = STATE(33),
    [sym_opType] = STATE(33),
    [sym_earlyOpType] = STATE(24),
    [sym_opSet] = STATE(33),
    [sym_opCall] = STATE(33),
    [sym_opBuiltin] = STATE(33),
    [sym_opBranch] = STATE(33),
    [sym_opAlu] = STATE(33),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(5),
    [anon_sym_DOLLAR] = ACTIONS(7),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_lineComment] = ACTIONS(19),
    [sym_docComment] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(25), 1,
      anon_sym_AT,
    ACTIONS(28), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    ACTIONS(34), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_PIPE,
    ACTIONS(40), 1,
      anon_sym_QMARK,
    ACTIONS(43), 1,
      anon_sym_POUND,
    ACTIONS(46), 1,
      sym_lineComment,
    ACTIONS(49), 1,
      sym_docComment,
    STATE(24), 1,
      sym_earlyOpType,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(2), 3,
      sym__line,
      sym_op,
      aux_sym_source_file_repeat1,
    STATE(33), 7,
      sym_opDecl,
      sym_opType,
      sym_opSet,
      sym_opCall,
      sym_opBuiltin,
      sym_opBranch,
      sym_opAlu,
  [49] = 13,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_PIPE,
    ACTIONS(15), 1,
      anon_sym_QMARK,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    ACTIONS(54), 1,
      sym_lineComment,
    ACTIONS(56), 1,
      sym_docComment,
    STATE(24), 1,
      sym_earlyOpType,
    STATE(2), 3,
      sym__line,
      sym_op,
      aux_sym_source_file_repeat1,
    STATE(33), 7,
      sym_opDecl,
      sym_opType,
      sym_opSet,
      sym_opCall,
      sym_opBuiltin,
      sym_opBranch,
      sym_opAlu,
  [97] = 13,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_PIPE,
    ACTIONS(15), 1,
      anon_sym_QMARK,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(54), 1,
      sym_lineComment,
    ACTIONS(56), 1,
      sym_docComment,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      sym_earlyOpType,
    STATE(2), 3,
      sym__line,
      sym_op,
      aux_sym_source_file_repeat1,
    STATE(33), 7,
      sym_opDecl,
      sym_opType,
      sym_opSet,
      sym_opCall,
      sym_opBuiltin,
      sym_opBranch,
      sym_opAlu,
  [145] = 13,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_PIPE,
    ACTIONS(15), 1,
      anon_sym_QMARK,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    ACTIONS(62), 1,
      sym_lineComment,
    ACTIONS(64), 1,
      sym_docComment,
    STATE(24), 1,
      sym_earlyOpType,
    STATE(3), 3,
      sym__line,
      sym_op,
      aux_sym_source_file_repeat1,
    STATE(33), 7,
      sym_opDecl,
      sym_opType,
      sym_opSet,
      sym_opCall,
      sym_opBuiltin,
      sym_opBranch,
      sym_opAlu,
  [193] = 4,
    ACTIONS(68), 1,
      anon_sym_DOT,
    ACTIONS(71), 1,
      sym_docComment,
    STATE(6), 1,
      aux_sym__scopePath_repeat1,
    ACTIONS(66), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [217] = 4,
    ACTIONS(75), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      sym_docComment,
    STATE(8), 1,
      aux_sym__scopePath_repeat1,
    ACTIONS(73), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [241] = 4,
    ACTIONS(75), 1,
      anon_sym_DOT,
    ACTIONS(81), 1,
      sym_docComment,
    STATE(6), 1,
      aux_sym__scopePath_repeat1,
    ACTIONS(79), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [265] = 2,
    ACTIONS(71), 1,
      sym_docComment,
    ACTIONS(66), 13,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_lineComment,
  [284] = 2,
    ACTIONS(85), 1,
      sym_docComment,
    ACTIONS(83), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [302] = 2,
    ACTIONS(89), 1,
      sym_docComment,
    ACTIONS(87), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [320] = 4,
    ACTIONS(93), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      sym_docComment,
    STATE(13), 1,
      aux_sym__params_repeat1,
    ACTIONS(91), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [342] = 4,
    ACTIONS(93), 1,
      anon_sym_COMMA,
    ACTIONS(99), 1,
      sym_docComment,
    STATE(15), 1,
      aux_sym__params_repeat1,
    ACTIONS(97), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [364] = 2,
    ACTIONS(103), 1,
      sym_docComment,
    ACTIONS(101), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [382] = 4,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      sym_docComment,
    STATE(15), 1,
      aux_sym__params_repeat1,
    ACTIONS(105), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [404] = 2,
    ACTIONS(114), 1,
      sym_docComment,
    ACTIONS(112), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [422] = 7,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(122), 1,
      sym_literalNumber,
    STATE(43), 1,
      sym__params,
    ACTIONS(120), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(12), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [449] = 7,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(122), 1,
      sym_literalNumber,
    STATE(42), 1,
      sym__params,
    ACTIONS(120), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(12), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [476] = 3,
    ACTIONS(126), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      sym_docComment,
    ACTIONS(124), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [495] = 2,
    ACTIONS(110), 1,
      sym_docComment,
    ACTIONS(105), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [512] = 7,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(122), 1,
      sym_literalNumber,
    STATE(29), 1,
      sym__params,
    ACTIONS(120), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(12), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [539] = 7,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(122), 1,
      sym_literalNumber,
    STATE(32), 1,
      sym__params,
    ACTIONS(120), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(12), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [566] = 7,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(122), 1,
      sym_literalNumber,
    STATE(36), 1,
      sym__params,
    ACTIONS(120), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(12), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [593] = 3,
    ACTIONS(132), 1,
      anon_sym_SEMI,
    ACTIONS(134), 1,
      sym_docComment,
    ACTIONS(130), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [612] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(138), 1,
      sym_literalNumber,
    ACTIONS(136), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(62), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [636] = 2,
    ACTIONS(142), 1,
      sym_docComment,
    ACTIONS(140), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [652] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(146), 1,
      sym_literalNumber,
    ACTIONS(144), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(58), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [676] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(150), 1,
      sym_literalNumber,
    ACTIONS(148), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(20), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [700] = 2,
    ACTIONS(154), 1,
      sym_docComment,
    ACTIONS(152), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [716] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(158), 1,
      sym_literalNumber,
    ACTIONS(156), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(19), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [740] = 2,
    ACTIONS(162), 1,
      sym_docComment,
    ACTIONS(160), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [756] = 2,
    ACTIONS(166), 1,
      sym_docComment,
    ACTIONS(164), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [772] = 2,
    ACTIONS(170), 1,
      sym_docComment,
    ACTIONS(168), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [788] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(174), 1,
      sym_literalNumber,
    ACTIONS(172), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(52), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [812] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(178), 1,
      sym_literalNumber,
    ACTIONS(176), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(31), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [836] = 2,
    ACTIONS(182), 1,
      sym_docComment,
    ACTIONS(180), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [852] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(186), 1,
      sym_literalNumber,
    ACTIONS(184), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(59), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [876] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(190), 1,
      sym_literalNumber,
    ACTIONS(188), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(60), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [900] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(194), 1,
      sym_literalNumber,
    ACTIONS(192), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(61), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [924] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(198), 1,
      sym_literalNumber,
    ACTIONS(196), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(16), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [948] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(202), 1,
      sym_literalNumber,
    ACTIONS(200), 3,
      sym_ident,
      sym_literalString,
      sym_literalDecimal,
    STATE(26), 4,
      sym_block,
      sym_earlyOpType,
      sym__expr,
      sym_scope,
  [972] = 2,
    ACTIONS(206), 1,
      sym_docComment,
    ACTIONS(204), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [988] = 2,
    ACTIONS(210), 1,
      sym_docComment,
    ACTIONS(208), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_TILDE,
      anon_sym_BANG,
      anon_sym_PIPE,
      anon_sym_QMARK,
      anon_sym_POUND,
      sym_lineComment,
  [1004] = 3,
    ACTIONS(214), 1,
      anon_sym_STAR,
    STATE(56), 1,
      sym_aluFunc,
    ACTIONS(212), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
  [1020] = 6,
    ACTIONS(216), 1,
      anon_sym_STAR,
    ACTIONS(218), 1,
      anon_sym_CARET,
    ACTIONS(220), 1,
      anon_sym__,
    ACTIONS(222), 1,
      sym_ident,
    STATE(47), 1,
      aux_sym__modifierScope_repeat1,
    STATE(48), 2,
      sym__modifierScope,
      sym__identScope,
  [1040] = 3,
    ACTIONS(224), 1,
      anon_sym_STAR,
    STATE(46), 1,
      aux_sym__modifierScope_repeat1,
    ACTIONS(227), 2,
      anon_sym_DOT,
      sym_ident,
  [1051] = 4,
    ACTIONS(229), 1,
      anon_sym_STAR,
    ACTIONS(231), 1,
      anon_sym_DOT,
    ACTIONS(233), 1,
      sym_ident,
    STATE(46), 1,
      aux_sym__modifierScope_repeat1,
  [1064] = 2,
    ACTIONS(235), 1,
      sym_ident,
    STATE(10), 1,
      sym__scopePath,
  [1071] = 2,
    ACTIONS(231), 1,
      anon_sym_DOT,
    ACTIONS(233), 1,
      sym_ident,
  [1078] = 1,
    ACTIONS(237), 1,
      sym_ident,
  [1082] = 1,
    ACTIONS(239), 1,
      sym_ident,
  [1086] = 1,
    ACTIONS(241), 1,
      anon_sym_COMMA,
  [1090] = 1,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
  [1094] = 1,
    ACTIONS(245), 1,
      sym_ident,
  [1098] = 1,
    ACTIONS(247), 1,
      anon_sym_DOT,
  [1102] = 1,
    ACTIONS(249), 1,
      anon_sym_SEMI,
  [1106] = 1,
    ACTIONS(251), 1,
      anon_sym_SEMI,
  [1110] = 1,
    ACTIONS(253), 1,
      anon_sym_SEMI,
  [1114] = 1,
    ACTIONS(255), 1,
      anon_sym_SEMI,
  [1118] = 1,
    ACTIONS(257), 1,
      anon_sym_SEMI,
  [1122] = 1,
    ACTIONS(259), 1,
      anon_sym_SEMI,
  [1126] = 1,
    ACTIONS(261), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 97,
  [SMALL_STATE(5)] = 145,
  [SMALL_STATE(6)] = 193,
  [SMALL_STATE(7)] = 217,
  [SMALL_STATE(8)] = 241,
  [SMALL_STATE(9)] = 265,
  [SMALL_STATE(10)] = 284,
  [SMALL_STATE(11)] = 302,
  [SMALL_STATE(12)] = 320,
  [SMALL_STATE(13)] = 342,
  [SMALL_STATE(14)] = 364,
  [SMALL_STATE(15)] = 382,
  [SMALL_STATE(16)] = 404,
  [SMALL_STATE(17)] = 422,
  [SMALL_STATE(18)] = 449,
  [SMALL_STATE(19)] = 476,
  [SMALL_STATE(20)] = 495,
  [SMALL_STATE(21)] = 512,
  [SMALL_STATE(22)] = 539,
  [SMALL_STATE(23)] = 566,
  [SMALL_STATE(24)] = 593,
  [SMALL_STATE(25)] = 612,
  [SMALL_STATE(26)] = 636,
  [SMALL_STATE(27)] = 652,
  [SMALL_STATE(28)] = 676,
  [SMALL_STATE(29)] = 700,
  [SMALL_STATE(30)] = 716,
  [SMALL_STATE(31)] = 740,
  [SMALL_STATE(32)] = 756,
  [SMALL_STATE(33)] = 772,
  [SMALL_STATE(34)] = 788,
  [SMALL_STATE(35)] = 812,
  [SMALL_STATE(36)] = 836,
  [SMALL_STATE(37)] = 852,
  [SMALL_STATE(38)] = 876,
  [SMALL_STATE(39)] = 900,
  [SMALL_STATE(40)] = 924,
  [SMALL_STATE(41)] = 948,
  [SMALL_STATE(42)] = 972,
  [SMALL_STATE(43)] = 988,
  [SMALL_STATE(44)] = 1004,
  [SMALL_STATE(45)] = 1020,
  [SMALL_STATE(46)] = 1040,
  [SMALL_STATE(47)] = 1051,
  [SMALL_STATE(48)] = 1064,
  [SMALL_STATE(49)] = 1071,
  [SMALL_STATE(50)] = 1078,
  [SMALL_STATE(51)] = 1082,
  [SMALL_STATE(52)] = 1086,
  [SMALL_STATE(53)] = 1090,
  [SMALL_STATE(54)] = 1094,
  [SMALL_STATE(55)] = 1098,
  [SMALL_STATE(56)] = 1102,
  [SMALL_STATE(57)] = 1106,
  [SMALL_STATE(58)] = 1110,
  [SMALL_STATE(59)] = 1114,
  [SMALL_STATE(60)] = 1118,
  [SMALL_STATE(61)] = 1122,
  [SMALL_STATE(62)] = 1126,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(25),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(40),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(39),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(38),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(27),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(44),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scopePath_repeat1, 2),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scopePath_repeat1, 2), SHIFT_REPEAT(54),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__scopePath_repeat1, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scopePath, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__scopePath, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scopePath, 2),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__scopePath, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, .production_id = 2),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope, 3, .production_id = 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__params, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__params, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__params, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__params, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__params_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__params_repeat1, 2), SHIFT_REPEAT(28),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__params_repeat1, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_earlyOpType, 2, .production_id = 1),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_earlyOpType, 2, .production_id = 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opDecl, 4, .production_id = 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opDecl, 4, .production_id = 3),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opType, 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opType, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opBranch, 6, .production_id = 6),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opBranch, 6, .production_id = 6),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opAlu, 4, .production_id = 4),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opAlu, 4, .production_id = 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opDecl, 6, .production_id = 5),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opDecl, 6, .production_id = 5),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opBuiltin, 4, .production_id = 1),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opBuiltin, 4, .production_id = 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op, 1),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_op, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opType, 3),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opType, 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opSet, 4, .production_id = 1),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opSet, 4, .production_id = 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opCall, 4, .production_id = 1),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opCall, 4, .production_id = 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__modifierScope_repeat1, 2), SHIFT_REPEAT(46),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__modifierScope_repeat1, 2),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__modifierScope, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__identScope, 2),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__modifierScope, 2),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [243] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aluFunc, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_endron(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
